# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be2c2d0e369304e91ae96cf0fb8a0805fa29b0f5182029b9ab6a9e138fcb5e6517a98ab35b44c1f2feff14b3a069116f8147c5e9d630e43d44f55a1fedee699

test:
  secret_key_base: 78396c259521498b816987a9b15e5a56793cf10686bb61e06e425d5ac0baebdc2ec5bad1b01efb6284ec9a9534d3891fac33227f424445b798800f86e6ff0438

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
